theme: jekyll-theme-minimal
title: Hello, I'm Vignesh
description: myCustomAndDetailedDescription
logo: https://github.com/IamVigneshC/IamVigneshC.github.io/blob/main/about/PhotoRoom_20200925_185152.jpg
show_downloads: "True"
