theme: jekyll-theme-minimal
title: Hello, I'm Vignesh
description: myCustomAndDetailedDescription
logo: https://github.com/IamVigneshC/IamVigneshC.github.io/blob/main/about/Screen%20Shot%202020-11-27%20at%2012.46.00%20PM.png

