theme: jekyll-theme-minimal
title: Hello, I'm Vignesh
description: I intend to improve myself everyday. I don't compete, I overcome! I don't settle for ordinary, I strive to be the best! I don't thrive, I excel!!
logo: /about/1.png

